version: '3.6'

services:
#  mysql:
#    image: mysql:5.6
#    environment:
#      - MYSQL_ROOT_PASSWORD=my-secret-pw
#    restart: always
#    volumes:
#      - db_data:/var/lib/mysql
  ipam:
#    depends_on:
#      - mysql
    image: vortexict/phpipam:latest
    container_name: ipam
    environment:
      - MYSQL_USER=phpipam_root
      - MYSQL_PASSWORD=PhP-1358
      - MYSQL_HOST=63.32.32.176
      - MYSQL_DB=phpipam
      - MYSQL_PORT=3306
    ports:
      - "80:80"
volumes:
  db_data: